#!/usr/bin/env node

const uppercase = "ABCDEFGHIJKLMNOPQRSTUVWXYZ".split("");
const lowercase = "abcdefghijklmnopqrstuvwxyz".split("");
const digits = "0123456789".split("");
const special = "!@$%^&*()[]{}_-:;~ ".split("");
const randomFrom = (min, max) =>
	Math.floor(Math.random() * (max - min + 1) + min);
const randomItem = (list) => list[Math.floor(Math.random() * list.length)];
const generate = () =>
	[
		Array.from({ length: randomFrom(3, 5) }).map(() => randomItem(lowercase)),
		randomItem(special),
		Array.from({ length: randomFrom(3, 5) }).map(() => randomItem(digits)),
		randomItem(special),
		Array.from({ length: randomFrom(3, 5) }).map(() => randomItem(uppercase)),
		randomItem(special),
		Array.from({ length: randomFrom(3, 5) }).map(() => randomItem(lowercase)),
	]
		.flat()
		.join("");
const password = generate();

console.log(password, "\n", password.length);
